Fikser duplicate landmark som slår ut på Svar på søknad headeren
navikt/spinnsyn-frontend pull request #1467
Opened 2023-11-29 09:16 UTC by golshidb93

2023-12-14 13:56 UTC, heyvard commented on src/components/vedtak-side/utbetaling/refusjon-med-inntekt.tsx
> +                                (annullert eller revidert)
hmm. jeg tror ikke de med skjermleser forstår disse ordene.  Og er det ikke mulig å bruke sr-only her også?

2023-12-14 13:58 UTC, golshidb93 commented on src/components/vedtak-side/utbetaling/refusjon-med-inntekt.tsx
> +                                (annullert eller revidert)
jeg hadde endret det til sr-only, men det ble ikke med kanskje fordi jeg rebaset 🤔

2023-12-14 14:06 UTC, heyvard requested changes

2023-12-14 14:06 UTC, heyvard commented on src/components/vedtak-side/utbetaling/refusjon-med-inntekt.tsx
> +                            <span className="sr-only">(annullert eller revudert)</span>
Det er typo i revurdert. Mangler en r. Og så tenker jeg at vi bør bruke teksten "Behandlet på nytt" . Revurdert og annullert viser vi aldri til brukeren

2023-12-15 08:47 UTC, heyvard approved these changes

2023-12-15 08:48 UTC, merged