Fikser feil bruk av feil dato i sykepengedato
navikt/spinnsyn-frontend pull request #722
Opened 2023-02-28 14:07 UTC by oivindkulsrud

2023-02-28 18:12 UTC, heyvard requested changes

2023-02-28 18:12 UTC, heyvard commented on src/components/vedtak-side/sykepengedager/sykepengedager.tsx
>      const vedtaktsdato = tilLesbarDatoMedArstall(dayjs(vedtak?.opprettetTimestamp).toDate())
github sier denne ikke er i bruk lengre

2023-03-01 08:24 UTC, kulsveen approved these changes

2023-03-01 10:54 UTC, oivindkulsrud commented on src/components/vedtak-side/sykepengedager/sykepengedager.tsx
>      const vedtaktsdato = tilLesbarDatoMedArstall(dayjs(vedtak?.opprettetTimestamp).toDate())
takk, fikset

2023-03-01 11:08 UTC, heyvard approved these changes

2023-03-01 11:08 UTC, merged